// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: hls.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewHlsStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId   string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StreamKey  string `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	ServerUrl  string `protobuf:"bytes,3,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	Resolution int32  `protobuf:"varint,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Fps        int32  `protobuf:"varint,5,opt,name=fps,proto3" json:"fps,omitempty"`
}

func (x *NewHlsStreamReq) Reset() {
	*x = NewHlsStreamReq{}
	mi := &file_hls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewHlsStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHlsStreamReq) ProtoMessage() {}

func (x *NewHlsStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_hls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHlsStreamReq.ProtoReflect.Descriptor instead.
func (*NewHlsStreamReq) Descriptor() ([]byte, []int) {
	return file_hls_proto_rawDescGZIP(), []int{0}
}

func (x *NewHlsStreamReq) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *NewHlsStreamReq) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *NewHlsStreamReq) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *NewHlsStreamReq) GetResolution() int32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *NewHlsStreamReq) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

type NewHlsStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewHlsStreamResp) Reset() {
	*x = NewHlsStreamResp{}
	mi := &file_hls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewHlsStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHlsStreamResp) ProtoMessage() {}

func (x *NewHlsStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_hls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHlsStreamResp.ProtoReflect.Descriptor instead.
func (*NewHlsStreamResp) Descriptor() ([]byte, []int) {
	return file_hls_proto_rawDescGZIP(), []int{1}
}

var File_hls_proto protoreflect.FileDescriptor

var file_hls_proto_rawDesc = []byte{
	0x0a, 0x09, 0x68, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x9e, 0x01, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x48, 0x6c, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4b, 0x65, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x66, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x66, 0x70, 0x73,
	0x22, 0x12, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x48, 0x6c, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x32, 0x47, 0x0a, 0x0a, 0x48, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x48, 0x6c, 0x73, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x77, 0x48, 0x6c, 0x73, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x77,
	0x48, 0x6c, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x42, 0x05, 0x5a,
	0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hls_proto_rawDescOnce sync.Once
	file_hls_proto_rawDescData = file_hls_proto_rawDesc
)

func file_hls_proto_rawDescGZIP() []byte {
	file_hls_proto_rawDescOnce.Do(func() {
		file_hls_proto_rawDescData = protoimpl.X.CompressGZIP(file_hls_proto_rawDescData)
	})
	return file_hls_proto_rawDescData
}

var file_hls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hls_proto_goTypes = []any{
	(*NewHlsStreamReq)(nil),  // 0: pb.NewHlsStreamReq
	(*NewHlsStreamResp)(nil), // 1: pb.NewHlsStreamResp
}
var file_hls_proto_depIdxs = []int32{
	0, // 0: pb.HlsService.NewHlsStream:input_type -> pb.NewHlsStreamReq
	1, // 1: pb.HlsService.NewHlsStream:output_type -> pb.NewHlsStreamResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hls_proto_init() }
func file_hls_proto_init() {
	if File_hls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hls_proto_goTypes,
		DependencyIndexes: file_hls_proto_depIdxs,
		MessageInfos:      file_hls_proto_msgTypes,
	}.Build()
	File_hls_proto = out.File
	file_hls_proto_rawDesc = nil
	file_hls_proto_goTypes = nil
	file_hls_proto_depIdxs = nil
}
