// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/hls.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HlsService_NewHlsStream_FullMethodName = "/pb.HlsService/NewHlsStream"
)

// HlsServiceClient is the client API for HlsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HlsServiceClient interface {
	NewHlsStream(ctx context.Context, in *NewHlsStreamReq, opts ...grpc.CallOption) (*NewHlsStreamResp, error)
}

type hlsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHlsServiceClient(cc grpc.ClientConnInterface) HlsServiceClient {
	return &hlsServiceClient{cc}
}

func (c *hlsServiceClient) NewHlsStream(ctx context.Context, in *NewHlsStreamReq, opts ...grpc.CallOption) (*NewHlsStreamResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewHlsStreamResp)
	err := c.cc.Invoke(ctx, HlsService_NewHlsStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HlsServiceServer is the server API for HlsService service.
// All implementations should embed UnimplementedHlsServiceServer
// for forward compatibility.
type HlsServiceServer interface {
	NewHlsStream(context.Context, *NewHlsStreamReq) (*NewHlsStreamResp, error)
}

// UnimplementedHlsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHlsServiceServer struct{}

func (UnimplementedHlsServiceServer) NewHlsStream(context.Context, *NewHlsStreamReq) (*NewHlsStreamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewHlsStream not implemented")
}
func (UnimplementedHlsServiceServer) testEmbeddedByValue() {}

// UnsafeHlsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HlsServiceServer will
// result in compilation errors.
type UnsafeHlsServiceServer interface {
	mustEmbedUnimplementedHlsServiceServer()
}

func RegisterHlsServiceServer(s grpc.ServiceRegistrar, srv HlsServiceServer) {
	// If the following call pancis, it indicates UnimplementedHlsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HlsService_ServiceDesc, srv)
}

func _HlsService_NewHlsStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewHlsStreamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HlsServiceServer).NewHlsStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HlsService_NewHlsStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HlsServiceServer).NewHlsStream(ctx, req.(*NewHlsStreamReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HlsService_ServiceDesc is the grpc.ServiceDesc for HlsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HlsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HlsService",
	HandlerType: (*HlsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewHlsStream",
			Handler:    _HlsService_NewHlsStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hls.proto",
}
